apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-dp
 labels:
  app: nginx-app
spec:
 template:
  metadata:
   name: nginx
   labels:
    app: nginx-app
  spec:
   containers:
    - name: nginx
      image: nginx
 replicas: 1
 selector:
  matchLabels:
   app: nginx-app

    