apiVersion: v1
kind: Service
metadata:
 name: user-account
 labels:
  app: user-account-key
spec:
 type: NodePort
 ports:
  - targetPort: 8081
    port: 8081
    protocol: TCP
    name: http
 selector:
  app: details-app-key