apiVersion: v1
kind: Service
metadata:
 name: user-balance
 labels:
  app: user-balance-key
spec:
 type: ClusterIP
 ports:
  - targetPort: 8010
    port: 8010
 selector:
  app: balance-app-key
  