apiVersion: v1
kind: Service
metadata:
 name: user-balance-node
 labels:
  app: user-balance-key-node
spec:
 type: NodePort
 ports:
  - targetPort: 8010
    port: 8010
 selector:
  app: balance-app-key
  